package io.github.maxwellnie.jorm.test.statement;

import io.github.maxwellnie.jorm.core.sql.batch.BatchSql;
import io.github.maxwellnie.jorm.core.sql.batch.BatchSqlBuilder;
import io.github.maxwellnie.jorm.core.sql.single.SingleSql;
import io.github.maxwellnie.jorm.core.sql.single.SingleSqlBuilder;
import io.github.maxwellnie.jorm.core.sql.statement.*;
import io.github.maxwellnie.jorm.test.DBUtils;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.List;

/**
 * @author Maxwell Nie
 */
public class PreparedStatementTest {
    public static final Executor<PreparedStatement, Void> RP = (statement, sql) -> {
        System.out.println(statement.executeUpdate());
        return null;
    };
    public static final ParameterHandler<PreparedStatement, SingleSql> PARAMETERS_HANDLER = (statement, sql) -> {
        for (int i = 0; i < sql.getSqlParameters().size(); i++) {
            statement.setObject(i + 1, sql.getSqlParameters().get(i));
        }
    };
    public static final ParameterHandler<PreparedStatement, BatchSql> BATCH_PARAMETERS_HANDLER = (statement, sql) -> {
        for (int i = 0; i < sql.getParamsLists().size(); i++) {
            List<Object> parameters = sql.getParamsLists().get(i);
            for (int j = 0; j < parameters.size(); j++) {
                statement.setObject(j + 1, parameters.get(j));
            }
            statement.addBatch();
        }
    };
    public static final Configuration INSERT_CONFIGURATION = new ConfigurationImpl()
            .setAutoGeneratedKeys(Statement.RETURN_GENERATED_KEYS);
    public static void testInsert() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder(3)
                .appendSql("insert into tb_user(loginname, `password`, role_id) values (?, ?, ?)")
                .appendSqlParameters("hello jorm!", 112233, 1)
                .build();
        DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .setConfiguration(INSERT_CONFIGURATION)
                .createStatement(singleSql.getSqlString())
                .parameterize(PARAMETERS_HANDLER, singleSql)
                .handleStatement((ps) -> {
                    ps.setQueryTimeout(1);
                }),
                is-> {
                    is.execute(RP);
                    ResultSet rs = is.getStatement().getGeneratedKeys();
                    while (rs.next()){
                        System.out.println(rs.getInt(1));
                    }
                    rs.close();
                }
        );
    }
    public static void testUpdate() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder(3)
                .appendSql("update tb_user set loginname = ?, `password` = ?, role_id = ? where user_id = ?")
                .appendSqlParameters("hello jorm!", 112233, 1, 536)
                .build();
        DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .createStatement(singleSql.getSqlString())
                .parameterize(PARAMETERS_HANDLER, singleSql)
                , is-> is.execute(RP));
    }
    public static void testDelete() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder(1)
                .appendSql("delete from tb_user where user_id = ?")
                .appendSqlParameters(538)
                .build();
        DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .createStatement(singleSql.getSqlString())
                .parameterize(PARAMETERS_HANDLER, singleSql)
                , is-> is.execute(RP));
    }
    public static void testQuery() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder()
                .appendSql("select * from tb_user")
                .build();
        DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .createStatement(singleSql.getSqlString())
                , is-> is.execute(new ResultParser<PreparedStatement, Void, Void>() {
                    @Override
                    public Void parse(PreparedStatement statement, Void parameters) {
                        try (ResultSet rs = statement.getResultSet();){

                            if (rs ==  null)
                                throw new ResultParseException("ResultSet is null");
                            System.out.println("==========================================");
                            while (rs.next()) {
                                System.out.print(rs.getInt(1)+",");
                                System.out.print(rs.getString(2)+",");
                                System.out.print(rs.getString(3)+",");
                                System.out.print(rs.getInt(4)+"\n");
                            }
                            System.out.println("==========================================");
                            return null;
                        } catch (SQLException e) {
                            throw new ResultParseException(e);
                        }
                    }
                }));
    }
    public static void testBatchInsert() throws SQLException {
        BatchSql batchSql = new BatchSqlBuilder(2, 3)
                .appendSql("insert into tb_user(loginname, `password`, role_id) values (?, ?, ?)")
                .appendBatchSqlParameters("hello jorm!", 112233, 1)
                .appendBatchSqlParameters("hello jorm!", 112233, 1)
                .build();
        DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .setConfiguration(INSERT_CONFIGURATION)
                .createStatement(batchSql.getSqlString())
                .parameterize(BATCH_PARAMETERS_HANDLER, batchSql)
                , is-> {
                    System.out.println(Arrays.toString(is.execute(Executor.PREPARED_STATEMENT_BATCH_EXECUTOR)));
                    ResultSet rs = is.getStatement().getGeneratedKeys();
                    while (rs.next()){
                        System.out.println(rs.getInt(1));
                    }
                }
        );
    }
    public static void testBatchUpdate() throws SQLException {
        BatchSql batchSql = new BatchSqlBuilder(2, 4)
                .appendSql("update tb_user set loginname = ?, `password` = ?, role_id = ? where user_id = ?")
                .appendBatchSqlParameters("hello jorm!", 112233, 1, 539)
                .appendBatchSqlParameters("hello jorm!", 112233, 1, 540)
                .build();
                DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .createStatement(batchSql.getSqlString())
                .parameterize(BATCH_PARAMETERS_HANDLER, batchSql)
                , is-> System.out.println(Arrays.toString(is.execute(Executor.PREPARED_STATEMENT_BATCH_EXECUTOR))));
    }
    public static void testBatchDelete() throws SQLException {
        BatchSql batchSql = new BatchSqlBuilder(2, 1)
                .appendSql("delete from tb_user where user_id = ?")
                .appendBatchSqlParameters(539)
                .appendBatchSqlParameters(540)
                .build();
        DBUtils.execute(c-> new PreparedIntegratedStatement(c)
                .createStatement(batchSql.getSqlString())
                .parameterize(BATCH_PARAMETERS_HANDLER, batchSql)
                , is-> System.out.println(Arrays.toString(is.execute(Executor.PREPARED_STATEMENT_BATCH_EXECUTOR))));
    }
}
