package io.github.maxwellnie.jorm.test.statement;

import io.github.maxwellnie.jorm.core.sql.batch.BatchSql;
import io.github.maxwellnie.jorm.core.sql.batch.BatchSqlBuilder;
import io.github.maxwellnie.jorm.core.sql.single.SingleSql;
import io.github.maxwellnie.jorm.core.sql.single.SingleSqlBuilder;
import io.github.maxwellnie.jorm.core.sql.statement.*;
import io.github.maxwellnie.jorm.test.DBUtils;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;

/**
 * @author Maxwell Nie
 */
public class SimpleStatementTest {
    public static final IntegratedStatement.Executor<Statement, Void> RP = new IntegratedStatement.Executor<Statement, Void>() {
        @Override
        public Void execute(Statement statement, String sql) throws SQLException {
            System.out.println(statement.executeUpdate(sql));
            return null;
        }
    };
    public static void testInsert() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder()
                .appendSql("insert into tb_user(loginname, `password`, role_id) values ('jorm simpleStatementInsert()', '1122', 1)")
                .build();
        DBUtils.execute(c -> new SimpleIntegratedStatement(c)
                        .setConfiguration(new ConfigurationImpl().setAutoGeneratedKeys(Statement.RETURN_GENERATED_KEYS))
                        .createStatement(singleSql.getSqlString()),
                is -> is.execute(RP));
    }

    public static void testUpdate() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder()
                .appendSql("update tb_user set loginname = 'jorm simpleStatementUpdate()' where user_id = 533")
                .build();
        DBUtils.execute(
                c -> new SimpleIntegratedStatement(c)
                        .createStatement(singleSql.getSqlString()),
                is -> is.execute(RP)
        );
    }

    public static void testDelete() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder()
                .appendSql("delete from tb_user where user_id = 533")
                .build();
        DBUtils.execute(
                c -> new SimpleIntegratedStatement(c)
                        .createStatement(singleSql.getSqlString()),
                is -> is.execute(RP)
        );
    }

    public static void testQuery() throws SQLException {
        SingleSql singleSql = new SingleSqlBuilder()
                .appendSql("select * from tb_user")
                .build();
        DBUtils.execute(
                c -> new SimpleIntegratedStatement(c)
                        .createStatement(singleSql.getSqlString()),
                is -> is.execute(
                        new ResultParser<Statement, Void, Void>() {
                            @Override
                            public Void parse(Statement originalObject, Void parameters) throws ResultParserException {
                                try {
                                    ResultSet rs = originalObject.getResultSet();
                                    while (rs.next()) {
                                        System.out.println(rs.getInt(1)
                                                + " "
                                                + rs.getString(2)
                                                + " "
                                                + rs.getString(3));
                                    }
                                } catch (SQLException e) {
                                    throw new ResultParserException(e);
                                }
                                return null;
                            }
                        }
                )
        );
    }

    public static void testBatchInert() throws SQLException {
        BatchSql batchSql = new BatchSqlBuilder()
                .appendSql("insert into tb_user(loginname, `password`, role_id) values ('jorm simpleStatementBatch1()', '1122', 1);")
                .appendSql("insert into tb_user(loginname, `password`, role_id) values ('jorm simpleStatementBatch2()', '1122', 1);")
                .build();
        DBUtils.execute(
                c -> new SimpleIntegratedStatement(c)
                        .createStatement(batchSql.getSqlString()),
                is -> System.out.println(Arrays.toString(is.execute(IntegratedStatement.Executor.STATEMENT_BATCH_EXECUTOR)))
        );
    }

    public static void testBatchUpdate() throws SQLException {
        BatchSql batchSql = new BatchSqlBuilder()
                .appendSql("update tb_user set loginname = 'jorm simpleStatementBatchUpdate1()' where user_id = 534;")
                .appendSql("update tb_user set loginname = 'jorm simpleStatementBatchUpdate2()' where user_id = 535;")
                .build();
        DBUtils.execute(
                c -> new SimpleIntegratedStatement(c)
                        .createStatement(batchSql.getSqlString()),
                is -> System.out.println(Arrays.toString(is.execute(IntegratedStatement.Executor.STATEMENT_BATCH_EXECUTOR)))
        );
    }

    public static void testBatchDelete() throws SQLException {
        BatchSql batchSql = new BatchSqlBuilder()
                .appendSql("delete from tb_user where user_id = 534;")
                .appendSql("delete from tb_user where user_id = 535;")
                .build();
        DBUtils.execute(
                c -> new SimpleIntegratedStatement(c)
                        .createStatement(batchSql.getSqlString()),
                is -> System.out.println(Arrays.toString(is.execute(IntegratedStatement.Executor.STATEMENT_BATCH_EXECUTOR)))
        );
    }
}
