package io.github.maxwellnie.jorm.core.sql.statement;


/**
 * @author Maxwell Nie
 */
public interface Configuration {
    /**
     * @return <code>Statement.RETURN_GENERATED_KEYS</code> or <code>Statement.NO_GENERATED_KEYS</code>
     */
    int getAutoGeneratedKeys();

    int getFetchSize();

    int getQueryTimeout();

    int getResultSetConcurrency();

    int getResultSetType();

    int getHoldability();
}
