package io.github.maxwellnie.jorm.core.sql.statement;

/**
 * @author Maxwell Nie
 */
public class ConfigurationImpl implements Configuration {
    private int autoGeneratedKeys;
    private int fetchSize;
    private int queryTimeout;
    private int resultSetConcurrency;
    private int resultSetType;
    private int holdability;

    @Override
    public int getAutoGeneratedKeys() {
        return autoGeneratedKeys;
    }

    public ConfigurationImpl setAutoGeneratedKeys(int autoGeneratedKeys) {
        this.autoGeneratedKeys = autoGeneratedKeys;
        return this;
    }

    @Override
    public int getFetchSize() {
        return fetchSize;
    }

    public ConfigurationImpl setFetchSize(int fetchSize) {
        this.fetchSize = fetchSize;
        return this;
    }

    @Override
    public int getQueryTimeout() {
        return queryTimeout;
    }

    public ConfigurationImpl setQueryTimeout(int queryTimeout) {
        this.queryTimeout = queryTimeout;
        return this;
    }

    @Override
    public int getResultSetConcurrency() {
        return resultSetConcurrency;
    }

    public ConfigurationImpl setResultSetConcurrency(int resultSetConcurrency) {
        this.resultSetConcurrency = resultSetConcurrency;
        return this;
    }

    @Override
    public int getResultSetType() {
        return resultSetType;
    }

    public ConfigurationImpl setResultSetType(int resultSetType) {
        this.resultSetType = resultSetType;
        return this;
    }

    @Override
    public int getHoldability() {
        return holdability;
    }

    public ConfigurationImpl setHoldability(int holdability) {
        this.holdability = holdability;
        return this;
    }
}
