package io.github.maxwellnie.jorm.core.sql.statement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * @author Maxwell Nie
 */
public class PreparedIntegratedStatement extends BaseIntegratedStatement<PreparedStatement> {
    public PreparedIntegratedStatement(Connection connection) {
        super(connection);
    }

    @Override
    public IntegratedStatement<PreparedStatement> createStatement(String sql) throws StatementException {
        this.sql = sql;
        validateConnection();
        validateSql();
        try {
            if (configuration != null)
                statement = StatementUtils.prepareStatement(connection, sql, configuration.getAutoGeneratedKeys(), configuration.getResultSetType(), configuration.getResultSetConcurrency(), configuration.getHoldability());
            else
                statement = StatementUtils.prepareStatement(connection, sql);
        } catch (SQLException e) {
            throw new StatementException("Statement creation failed for SQL: " + sql, e);
        }
        return this;
    }

    protected boolean defaultExecute() throws SqlExecutionException {
        try {
            return statement.execute();
        } catch (SQLException e) {
            throw new SqlExecutionException("Statement execution failed for SQL: " + sql, e);
        }
    }

}
