package io.github.maxwellnie.jorm.core.sql.statement;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author Maxwell Nie
 */
public class SimpleIntegratedStatement extends BaseIntegratedStatement<Statement> {
    public SimpleIntegratedStatement(Connection connection) {
        super(connection);
    }

    @Override
    public IntegratedStatement<Statement> createStatement(String sql) throws StatementException {
        this.sql = sql;
        validateConnection();
        validateSql();
        try {
            if (configuration != null)
                statement = StatementUtils.statement(connection, configuration.getResultSetType(),
                        configuration.getResultSetConcurrency(), configuration.getHoldability());
            else
                statement = StatementUtils.statement(connection);
            applyConfiguration();
        } catch (SQLException e) {
            throw new StatementException("Statement creation failed for SQL: " + sql, e);
        }
        return this;
    }

    @Override
    public <P> IntegratedStatement<Statement> parameterize(ParameterHandler<Statement, P> parametersHandler, P parameters) throws StatementException {
        throw new StatementException("Statement parameterization is not supported");
    }

    @Override
    protected boolean defaultExecute() throws SqlExecutionException {
        try {
            if (configuration != null && configuration.getAutoGeneratedKeys() > 0){
                return statement.execute(sql, configuration.getAutoGeneratedKeys());
            }else
                return statement.execute(sql);
        } catch (SQLException e) {
            throw new SqlExecutionException("Statement execution failed for SQL: " + sql, e);
        }
    }
}
