package io.github.maxwellnie.jorm.core.sql.statement;

import java.sql.*;

/**
 * @author Maxwell Nie
 */
public interface StatementUtils {
    static PreparedStatement prepareStatement(Connection connection, String sql, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int holdability) throws SQLException {
        PreparedStatement preparedStatement;
        if (autoGeneratedKeys > 0)
            preparedStatement = connection.prepareStatement(sql, autoGeneratedKeys);
        else {
            if (resultSetType > 0 && resultSetConcurrency > 0) {
                if (holdability < 0) {
                    preparedStatement = connection.prepareStatement(sql, resultSetType, resultSetConcurrency);
                } else
                    preparedStatement = connection.prepareStatement(sql, resultSetType, resultSetConcurrency, holdability);
            } else {
                preparedStatement = connection.prepareStatement(sql);
            }
        }
        return preparedStatement;
    }

    static PreparedStatement prepareStatement(Connection connection, String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(connection, sql, autoGeneratedKeys, 0, 0, 0);
    }

    static Statement statement(Connection connection, int resultSetType, int resultSetConcurrency, int holdability) throws SQLException {
        Statement statement;
        if (resultSetType > 0 && resultSetConcurrency > 0) {
            if (holdability < 0)
                statement = connection.createStatement(resultSetType, resultSetConcurrency);
            else
                statement = connection.createStatement(resultSetType, resultSetConcurrency, holdability);
        } else {
            statement = connection.createStatement();
        }
        return statement;
    }

    static Statement statement(Connection connection) throws SQLException {
        return connection.createStatement();
    }

    static PreparedStatement prepareStatement(Connection connection, String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }
    static CallableStatement callableStatement(Connection connection, String sql) throws SQLException {
        return connection.prepareCall(sql);
    }
    static CallableStatement callableStatement(Connection connection, String sql, int resultSetType, int resultSetConcurrency, int holdability) throws SQLException {
        CallableStatement callableStatement;
        if (resultSetType > 0 && resultSetConcurrency > 0) {
            if (holdability < 0)
                callableStatement = connection.prepareCall(sql, resultSetType, resultSetConcurrency);
            else
                callableStatement = connection.prepareCall(sql, resultSetType, resultSetConcurrency, holdability);
        } else {
            callableStatement = connection.prepareCall(sql);
        }
        return callableStatement;
    }
}
